### ISSUE TITLE
希望自定义快捷键

### ISSUE THREAD

**Issue by 0000005** [jokimina/cbox-chrome-extension#1]
目前的快捷键Ctrl+Shift + K  与 edge的快捷键冲突。而edge的快捷键不支持自定义。这意味着在edge上，这款插件不可用。

**Comment by 0000005** [comment]
换一个快捷键也可以

**Comment by jokimina** [comment]
> 换一个快捷键也可以

这周末我添加下配置菜单，允许自定义快捷键，也欢迎pr哦～

**Comment by 0000005** [comment]
3Q

**Comment by jokimina** [comment]
> 3Q
<img width="451" alt="image" src="https://github.com/jokimina/cbox-chrome-extension/assets/11460661/7dd94f24-ca4b-42f5-8b14-1f8867319c9b">

抱歉出去旅了个游才回来。已经加上了自定义快捷键的功能，点击右上角扩展图标即可设置。

chrome webstore的版本也已经审核通过了，可以直接更新

**Comment by 0000005** [comment]
❤️

**Comment by liwuhou** [comment]
> > 3Q
> 
> <img alt="image" width="451" src="https://private-user-images.githubusercontent.com/11460661/293819345-7dd94f24-ca4b-42f5-8b14-1f8867319c9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNzY0NzAsIm5iZiI6MTcwNDM3NjE3MCwicGF0aCI6Ii8xMTQ2MDY2MS8yOTM4MTkzNDUtN2RkOTRmMjQtY2E0Yi00MmY1LThiMTQtMWY4ODY3MzE5YzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDEzNDkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZGNiNDNlM2NkNGI0YTJkYmZmNmNjNjU0YzMzNTM1YTQ1ZDIyZGU3NTQ3NzBjODk3ZTJlMGU3OGM3NDY2ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iMOByoQCAwmjD4Sb2pET5NVWwaPmzD-tJe7jmKW-HFM">
> 抱歉出去旅了个游才回来。已经加上了自定义快捷键的功能，点击右上角扩展图标即可设置。
> 
> chrome webstore 的版本也已经审核通过了，可以直接更新

大佬，mac的 command 键位好像设不了快捷键

**Comment by jokimina** [comment]
> > > 3Q
> > 
> > 
> > <img alt="image" width="451" src="https://private-user-images.githubusercontent.com/11460661/293819345-7dd94f24-ca4b-42f5-8b14-1f8867319c9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNzY0NzAsIm5iZiI6MTcwNDM3NjE3MCwicGF0aCI6Ii8xMTQ2MDY2MS8yOTM4MTkzNDUtN2RkOTRmMjQtY2E0Yi00MmY1LThiMTQtMWY4ODY3MzE5YzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDEzNDkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZGNiNDNlM2NkNGI0YTJkYmZmNmNjNjU0YzMzNTM1YTQ1ZDIyZGU3NTQ3NzBjODk3ZTJlMGU3OGM3NDY2ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iMOByoQCAwmjD4Sb2pET5NVWwaPmzD-tJe7jmKW-HFM">
> > 抱歉出去旅了个游才回来。已经加上了自定义快捷键的功能，点击右上角扩展图标即可设置。
> > chrome webstore 的版本也已经审核通过了，可以直接更新
> 
> 大佬，mac的 command 键位好像设不了快捷键

<img width="398" alt="image" src="https://github.com/jokimina/cbox-chrome-extension/assets/11460661/a0b83c1c-6fa9-4cbb-b409-ff3031cc11a0">

<img width="599" alt="image" src="https://github.com/jokimina/cbox-chrome-extension/assets/11460661/d6f8ffdf-3331-47a1-a554-f544f83e34b1">

https://github.com/jamiebuilds/tinykeys?tab=readme-ov-file#commonly-used-keys-and-codes

我刚试了下是可以的哦，Command对应的是`Meta`, 根据tinykeys的键位进行设置的，可以参考这个如上

**Comment by jokimina** [comment]
ps: 设置完后页面刷新一下才会生效
