### ISSUE TITLE
control+shift+k doesn't work anymore.

### ISSUE THREAD

**Issue by happy15** [jokimina/cbox-chrome-extension#3]
Hi there, first thanks for the great work.

But recently the control+shift+k doesn't work anymore. Both on chrome and edge.

The extension version is 1.0.7. 

Anything do you need to debug this?

**Comment by jokimina** [comment]
> Hi there, first thanks for the great work.
> 
> But recently the control+shift+k doesn't work anymore. Both on chrome and edge.
> 
> The extension version is 1.0.7.
> 
> Anything do you need to debug this?

Thank you for reporting the issue. I have just tested version 1.0.7, and indeed, there seems to be a bug occurring during the initial installation.

A temporary workaround is to click on the "Save" button once and then refresh the page.

I will work on fixing this issue and provide an update shortly.

**Comment by jokimina** [comment]
<img width="506" alt="image" src="https://github.com/jokimina/cbox-chrome-extension/assets/11460661/9b3f55d5-f75a-468c-9744-fa4026bb1d08">


> > Hi there, first thanks for the great work.
> > But recently the control+shift+k doesn't work anymore. Both on chrome and edge.
> > The extension version is 1.0.7.
> > Anything do you need to debug this?
> 
> Thank you for reporting the issue. I have just tested version 1.0.7, and indeed, there seems to be a bug occurring during the initial installation.
> 
> A temporary workaround is to click on the "Save" button once and then refresh the page.
> 
> I will work on fixing this issue and provide an update shortly.

**Comment by jokimina** [comment]
<img width="1112" alt="image" src="https://github.com/jokimina/cbox-chrome-extension/assets/11460661/3af78cd9-459b-49b3-bb5c-8021783e865f">

https://github.com/jokimina/cbox-chrome-extension/commit/f96e1c2fc462533e4da6ee557585fa624de8c40a

The fix commit has been pushed, and the updated version has been submitted for review in the app store.

**Comment by happy15** [comment]
> <img alt="image" width="506" src="https://private-user-images.githubusercontent.com/11460661/294386970-9b3f55d5-f75a-468c-9744-fa4026bb1d08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MjcwNTQsIm5iZiI6MTcwNDQyNjc1NCwicGF0aCI6Ii8xMTQ2MDY2MS8yOTQzODY5NzAtOWIzZjU1ZDUtZjc1YS00NjhjLTk3NDQtZmE0MDI2YmIxZDA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDAzNTIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZGRlYjQxMTAyYThjNmFkOTdiYmJjYzdjNjIwNzljZDdhNjcwZGQ5OWNlMTYwYjY0ZDk4NmU2MjVmZTc2NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j04ImQUAfBdKMNRlF7H4zzoDzYkZbkF_jj3DRHUpARw">
> > > Hi there, first thanks for the great work.
> > > But recently the control+shift+k doesn't work anymore. Both on chrome and edge.
> > > The extension version is 1.0.7.
> > > Anything do you need to debug this?
> > 
> > 
> > Thank you for reporting the issue. I have just tested version 1.0.7, and indeed, there seems to be a bug occurring during the initial installation.
> > A temporary workaround is to click on the "Save" button once and then refresh the page.
> > I will work on fixing this issue and provide an update shortly.

it works

> <img alt="image" width="1112" src="https://private-user-images.githubusercontent.com/11460661/294387960-3af78cd9-459b-49b3-bb5c-8021783e865f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MjcwNTksIm5iZiI6MTcwNDQyNjc1OSwicGF0aCI6Ii8xMTQ2MDY2MS8yOTQzODc5NjAtM2FmNzhjZDktNDU5Yi00OWIzLWJiNWMtODAyMTc4M2U4NjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDAzNTIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YTcwMzkwNTkzZjUxN2I3NjhhOTQ3NjI5MGUzNDllNzZmMDMzMjY3ODNmYmZjZTkxZDM3ZGQ1YjBmOGNkMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.USxQ8e4tqmdAXM7DTxebwzzNL29vxxfVjfcvLCwkcRE">
> [f96e1c2](https://github.com/jokimina/cbox-chrome-extension/commit/f96e1c2fc462533e4da6ee557585fa624de8c40a)
> 
> The fix commit has been pushed, and the updated version has been submitted for review in the app store.

looking forward to it.

**Comment by jokimina** [comment]
> > <img alt="image" width="506" src="https://private-user-images.githubusercontent.com/11460661/294386970-9b3f55d5-f75a-468c-9744-fa4026bb1d08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MjcwNTQsIm5iZiI6MTcwNDQyNjc1NCwicGF0aCI6Ii8xMTQ2MDY2MS8yOTQzODY5NzAtOWIzZjU1ZDUtZjc1YS00NjhjLTk3NDQtZmE0MDI2YmIxZDA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDAzNTIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZGRlYjQxMTAyYThjNmFkOTdiYmJjYzdjNjIwNzljZDdhNjcwZGQ5OWNlMTYwYjY0ZDk4NmU2MjVmZTc2NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j04ImQUAfBdKMNRlF7H4zzoDzYkZbkF_jj3DRHUpARw">
> > > > Hi there, first thanks for the great work.
> > > > But recently the control+shift+k doesn't work anymore. Both on chrome and edge.
> > > > The extension version is 1.0.7.
> > > > Anything do you need to debug this?
> > > 
> > > 
> > > Thank you for reporting the issue. I have just tested version 1.0.7, and indeed, there seems to be a bug occurring during the initial installation.
> > > A temporary workaround is to click on the "Save" button once and then refresh the page.
> > > I will work on fixing this issue and provide an update shortly.
> 
> it works
> 
> > <img alt="image" width="1112" src="https://private-user-images.githubusercontent.com/11460661/294387960-3af78cd9-459b-49b3-bb5c-8021783e865f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MjcwNTksIm5iZiI6MTcwNDQyNjc1OSwicGF0aCI6Ii8xMTQ2MDY2MS8yOTQzODc5NjAtM2FmNzhjZDktNDU5Yi00OWIzLWJiNWMtODAyMTc4M2U4NjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDAzNTIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YTcwMzkwNTkzZjUxN2I3NjhhOTQ3NjI5MGUzNDllNzZmMDMzMjY3ODNmYmZjZTkxZDM3ZGQ1YjBmOGNkMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.USxQ8e4tqmdAXM7DTxebwzzNL29vxxfVjfcvLCwkcRE">
> > [[f96e1c2](https://github.com/jokimina/cbox-chrome-extension/commit/f96e1c2fc462533e4da6ee557585fa624de8c40a)](https://github.com/jokimina/cbox-chrome-extension/commit/f96e1c2fc462533e4da6ee557585fa624de8c40a)
> > The fix commit has been pushed, and the updated version has been submitted for review in the app store.
> 
> looking forward to it.

<img width="561" alt="image" src="https://github.com/jokimina/cbox-chrome-extension/assets/11460661/874fdb37-2155-4a86-b867-2cc2fe65145a">

The store version has also been approved, and thank you again for your report.
