### ISSUE TITLE
自定義快捷方式未生效

### ISSUE THREAD

**Issue by 3ark1o1** [jokimina/cbox-chrome-extension#4]
chrome 自定義 快捷方式 或者 Cbox 自帶的自定義快捷方式均未生效。 按照要求刷新頁面，嘗試重啓chrome，恢復為默認 ctrl+shift+k 均未生效。
重新安裝Cbox 后只能使用默認快捷。

chrome 自定義后，只會打開 Cbox 快捷方式，而不是直接打開應用。

![image](https://github.com/jokimina/cbox-chrome-extension/assets/120381226/386d0db7-aa22-4684-982c-9c12243b4997)

另外：
https://www.quora.com/Is-there-a-way-to-do-text-search-across-all-open-tabs-in-Chrome
從這個需求來的，across all open tabs search in chrome, 例如 打開了 10個 tab, 要通過一個search 看3 個tab 裏是否有相似内容。 不是通過search bar 打開某個tab.
multi search 的幾個需求：
1. 單個頁面内的 多個搜索，目前 ctrl+f 只能單次搜索
2. 多個頁面單個搜索，檢索相似内容
3. 多個頁面多個搜索，檢索需要的内容，排除不需要的内容

**Comment by 3ark1o1** [comment]
Alt 大寫就解決了，好吧

那就煩請大佬看看 實際需求能否實現，或者有什麽使用建議。

**Comment by jokimina** [comment]
目前该插件只读取tab元信息，所以不太可能实现你所说的多页面内容搜索。

我查了下chrome商店， 下面这个search all tabs也许是你想要的

https://chromewebstore.google.com/detail/search-all-tabs/ndfnfhnlgoocpbbjjjfmiojdfcgcfomn
